using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
using Accounting101.Models;
using Accounting101.ValueConverters;
using Accounting101.ViewModels.Read;
using DataAccess.Models;
using DataAccess.Services.Interfaces;
using Microsoft.VisualStudio.Threading;

namespace Accounting101.Views.Read
{
    public partial class AccountsView : UserControl
    {
        public bool HasAccounts => _viewModel.HasAccounts;

        private readonly AccountsViewModel _viewModel = new();
        private readonly Brush _focusColor = Brushes.LightSlateGray;
        private readonly Binding _sbBinding = new("StartBalance") { Converter = new DecimalToAccountingStringConverter() };
        private readonly Binding _cbBinding = new("CurrentBalance") { Converter = new DecimalToAccountingStringConverter() };

        public AccountsView()
        {
            DataContext = _viewModel;
            InitializeComponent();
        }

        public void SetInfo(IDataStore dataStore, JoinableTaskFactory taskFactory, ClientWithInfo client)
        {
            _viewModel.SetInfo(dataStore, taskFactory, client);
        }

        private void DataGridAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            PropertyDescriptor propertyDescriptor = (PropertyDescriptor)e.PropertyDescriptor;
            e.Column.Header = propertyDescriptor.DisplayName;
            if (propertyDescriptor.DisplayName == "Id")
            {
                e.Cancel = true;
            }

            switch (propertyDescriptor.DisplayName)
            {
                case "StartBalance":
                    e.Column.Header = "Start Balance";
                    break;
                case "CurrentBalance":
                    e.Column.Header = "Current Balance";
                    break;
            }
        }

        private void AccountListLoadingRow(object? sender, DataGridRowEventArgs e)
        {
            e.Row.Background = Brushes.Transparent;
            e.Row.MouseEnter += (s, _) =>
            {
                e.Row.Background = _focusColor;
            };
            e.Row.MouseLeave += (s, _) =>
            {
                e.Row.Background = Brushes.Transparent;
            };
            e.Row.PreviewMouseDown += (s, _) =>
            {
                Guid accountId = ((AccountsViewLine)e.Row.Item).Id;
                _viewModel.ItemSelected(accountId);
            };
        }

        private void DataGridAutoGeneratedColumns(object? sender, EventArgs e)
        {
            if (sender is not DataGrid { Columns.Count: > 0 } dataGrid)
            {
                return;
            }

            DataGridColumn? sbColumn = dataGrid.Columns.FirstOrDefault(c => c.Header.ToString() == "Start Balance");
            DataGridColumn? cbColumn = dataGrid.Columns.FirstOrDefault(c => c.Header.ToString() == "Current Balance");

            ((DataGridTextColumn)sbColumn).Binding = _sbBinding;
            ((DataGridTextColumn)cbColumn).Binding = _cbBinding;

            Style style = new(typeof(DataGridCell), sbColumn.CellStyle);
            style.Setters.Add(new Setter
            {
                Property = HorizontalContentAlignmentProperty,
                Value = HorizontalAlignment.Right
            });

            sbColumn.CellStyle = style;
            cbColumn.CellStyle = style;
        }
    }
}