using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Accounting101.Messages;
using Accounting101.Models;
using Accounting101.ViewModels.Update;
using CommunityToolkit.Mvvm.Messaging;
using DataAccess.Models;
using DataAccess.Services.Interfaces;
using Microsoft.VisualStudio.Threading;

#pragma warning disable CS8618, CS9264

namespace Accounting101.Views.Update
{
    public partial class UpdateAccountTransactionsView : UserControl, IRecipient<UpdateTransactionLayoutMessage>
    {
        private readonly UpdateAccountTransactionsViewModel _viewModel = new();
        private IDataStore _dataStore;
        private JoinableTaskFactory _taskFactory;
        private List<AccountWithInfo> _otherAccounts;
        private Guid _accountId;
        private Style? _baseRowStyle;

        public UpdateAccountTransactionsView()
        {
            WeakReferenceMessenger.Default.RegisterAll(this);
            DataContext = _viewModel;
            InitializeComponent();
        }

        public void SetInfo(IDataStore dataStore, JoinableTaskFactory taskFactory, AccountWithTransactions account, List<AccountWithInfo> otherAccounts)
        {
            _dataStore = dataStore;
            _taskFactory = taskFactory;
            _accountId = account.Id;
            _otherAccounts = otherAccounts;
            _viewModel.SetInfo(account, otherAccounts);
        }

        public TransactionInfoLine? GetSelected()
        {
            return _viewModel.GetSelectedLine();
        }

        public void Receive(UpdateTransactionLayoutMessage message)
        {
            _viewModel.SetInfo(new AccountWithTransactions(_dataStore, _taskFactory, _accountId), _otherAccounts);
        }

        private void DataGridAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            PropertyDescriptor propertyDescriptor = (PropertyDescriptor)e.PropertyDescriptor;
            e.Column.Header = propertyDescriptor.DisplayName;
            switch (propertyDescriptor.DisplayName)
            {
                case "Id":
                    e.Cancel = true;
                    return;
                case "When":
                    {
                        e.Column.Header = "Date";
                        Style headerStyle = new();
                        headerStyle.Setters.Add(new Setter { Property = HorizontalContentAlignmentProperty, Value = HorizontalAlignment.Left });
                        e.Column.HeaderStyle = headerStyle;
                        break;
                    }
                case "Debit" or "Credit" or "Balance":
                    {
                        Style headerStyle = new();
                        headerStyle.Setters.Add(new Setter { Property = HorizontalContentAlignmentProperty, Value = HorizontalAlignment.Right });
                        e.Column.HeaderStyle = headerStyle;
                        break;
                    }
                case "OtherAccountInfo":
                    {
                        e.Column.Header = "Other Account";
                        Style headerStyle = new();
                        headerStyle.Setters.Add(new Setter { Property = HorizontalContentAlignmentProperty, Value = HorizontalAlignment.Right });
                        e.Column.HeaderStyle = headerStyle;
                        e.Column.Width = new DataGridLength(1, DataGridLengthUnitType.Star);
                        break;
                    }
            }
        }

        private void DataGridAutoGeneratedColumns(object? sender, EventArgs e)
        {
            if (sender is not DataGrid { Columns.Count: > 0 } dataGrid)
            {
                return;
            }

            DataGridColumn? firstColumn = dataGrid.Columns.First();
            DataGridColumn? creditColumn = dataGrid.Columns.First(c => c.Header.ToString() == "Credit");
            DataGridColumn? debitColumn = dataGrid.Columns.First(c => c.Header.ToString() == "Debit");
            DataGridColumn? balanceColumn = dataGrid.Columns.First(c => c.Header.ToString() == "Balance");
            DataGridColumn? lastColumn = dataGrid.Columns.Last();

            Style elementStyle = new(typeof(DataGridCell), firstColumn.CellStyle);
            firstColumn.CellStyle.Triggers.ToList().ForEach(t => elementStyle.Triggers.Add(t));

            elementStyle.Setters.Add(new Setter { Property = VerticalAlignmentProperty, Value = VerticalAlignment.Center });
            elementStyle.Setters.Add(new Setter { Property = IsTabStopProperty, Value = false });

            Trigger selectedTrigger = new() { Property = DataGridCell.IsSelectedProperty, Value = true };
            selectedTrigger.Setters.Add(new Setter { Property = BorderThicknessProperty, Value = new Thickness(0) });
            elementStyle.Triggers.Add(selectedTrigger);

            Trigger unselectedTrigger = new() { Property = DataGridCell.IsSelectedProperty, Value = false };
            unselectedTrigger.Setters.Add(new Setter { Property = BackgroundProperty, Value = Brushes.Transparent });
            elementStyle.Triggers.Add(unselectedTrigger);

            Style elementStyleLeft = new(typeof(DataGridCell), elementStyle);
            elementStyleLeft.Setters.Add(new Setter { Property = TextBlock.TextAlignmentProperty, Value = TextAlignment.Left });
            Style elementStyleRight = new(typeof(DataGridCell), elementStyle);
            elementStyleRight.Setters.Add(new Setter { Property = TextBlock.TextAlignmentProperty, Value = TextAlignment.Right });

            firstColumn.Width = new DataGridLength(1, DataGridLengthUnitType.Star);
            firstColumn.CellStyle = elementStyleLeft;
            creditColumn.Width = new DataGridLength(1, DataGridLengthUnitType.Star);
            creditColumn.CellStyle = elementStyleRight;
            debitColumn.Width = new DataGridLength(1, DataGridLengthUnitType.Star);
            debitColumn.CellStyle = elementStyleRight;
            balanceColumn.Width = new DataGridLength(1, DataGridLengthUnitType.Star);
            balanceColumn.CellStyle = elementStyleRight;
            lastColumn.Width = new DataGridLength(5, DataGridLengthUnitType.Star);
            lastColumn.CellStyle = elementStyleRight;
        }

        private void DataGridSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (sender is not DataGrid dataGrid)
            {
                return;
            }

            if (e.RemovedItems.Count > 0)
            {
                DataGridRow? removed = (DataGridRow)dataGrid.ItemContainerGenerator.ContainerFromItem(e.RemovedItems[0]);
                if (removed is not null)
                {
                    removed.Style = _baseRowStyle;
                }
            }
            if (dataGrid.SelectedItem is null)
            {
                return;
            }
            DataGridRow row = (DataGridRow)dataGrid.ItemContainerGenerator.ContainerFromItem(dataGrid.SelectedItem);
            _baseRowStyle ??= new Style(typeof(DataGridRow), row.Style);
            Style rowStyle = new(typeof(DataGridRow), _baseRowStyle);
            rowStyle.Setters.Add(new Setter { Property = BackgroundProperty, Value = Brushes.Red });
            row.Style = rowStyle;
        }
    }
}